include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI interface for GoWAN multi-WAN SOCKS5 balancer
LUCI_DEPENDS:=+gowan
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Ali Almohaya <ali.almohaya@anghami.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
